vti_encoding:SR|utf8-nl
vti_author:SR|NEXTECH\\hiroki-matsumoto
vti_modifiedby:SR|NEXTECH\\hiroki-matsumoto
vti_timelastmodified:TR|31 Jan 2010 23:30:43 -0000
vti_timecreated:TR|31 Jan 2010 23:29:12 -0000
vti_extenderversion:SR|12.0.0.6413
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TR|31 Jan 2010 23:30:35 -0000
vti_cacheddtm:TX|31 Jan 2010 23:30:43 -0000
vti_filesize:IR|224
